name: Build Lure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Visual Studio
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: 'latest'

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg integrate install

      - name: Install dependencies
        run: |
          .\vcpkg\vcpkg install

      - name: Build with MSBuild
        run: |
          msbuild Lure.sln /p:Configuration=Release

      - name: List directory contents to locate DLL
        run: |
          dir Lure /s

      - name: Upload DLL as artifact
        uses: actions/upload-artifact@v3
        with:
          name: Lure-dll
          path: Lure/**/Release/Lure.dll
